name: auto2
channels:
  - conda-forge
  - numba
dependencies:
  - python>=3.10
  - ipython
  - jupyter
  - matplotlib>=3.4
  - numpy
  - numba
  - scipy
  - sphinx
  - sphinx_rtd_theme>0.5.1
  - pytest
  - pip
  - pip:
      - sphinxcontrib-bibtex
      - nbmake
