name: pr-status

on:
  workflow_run:
    workflows: ["tests"]
    types:
      - completed
  
permissions:
  contents: read
  statuses: write

jobs:

  status:

    if: ${{ github.event.workflow_run.event == 'pull_request' }}

    name: Pull Request Status
    
    runs-on: ubuntu-latest

    steps:
      - name: Issue status
        shell: bash
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/Climdyn/auto-AUTO/statuses/${{ github.event.workflow_run.head_sha }} \
          -d '{"state":"${{ github.event.workflow_run.conclusion }}","target_url":"https://github.com/Climdyn/auto-AUTO/commit/${{ github.event.workflow_run.head_sha }}","description":"auto-AUTO tests results","context":"PR-status"}'
